### ISSUE TITLE
allow StackName as a parameter

### ISSUE THREAD

**Issue by fiducioso-dan** [brianneisler/gulp-cloudformation#2]
It would be helpful if the params object for the `.deploy()` function allowed me to specify the name of the CloudFormation stack. Currently it seems to pick based on the filename of the template file. This is an excellent default but doesn't allow you to run multiple CF stacks from the same template (e.g. for multiple environments dev/prod.)

This is what I get when I try passing StackName with a stack that already exists and template file `cloudformation.yml`:

```
ValidationError: Stack with id cloudformation does not exist
```

**Comment by brianneisler** [comment]
@fiducioso-dan good recommendation. Started working on a bit of a refactor to this module last night to incorporate some other improvements. I will work on adding in this parameter and potentially getting a new version released this weekend. 

Thanks for the issue report!

**Comment by brianneisler** [comment]
committed in c1cbe8da06a6e5e550aab2a46ed71989155a15f8

**Comment by brianneisler** [comment]
@fiducioso-dan sorry got busy with work and took me longer to get this out than I anticipated. New 0.1.0 version was just deployed with this feature.
